# /etc/dhcp/dhclient.conf に追記する
#
# フレッツ光ネクスト（NGN）からひかり電話の情報を DHCP オプションで受け取る設定
# 出典: voip-info.jp  http://www.voip-info.jp/index.php/%E5%88%A9%E7%94%A8%E8%80%85:Pin_ptr#DHCP
# 解説: docs/03-hikari-denwa.md

option ip-sip-servers code 120 = { boolean, array of ip-address };
option vendor-class.ntt code 210 = string;
option space ntt code width 1 length width 1 hash size 7;
option ntt.mac code 201 = string;
option ntt.number code 202 = text;
option ntt.domain code 204 = domain-list;
option ntt.firmware code 210 = domain-list;
option vendor.ntt code 210 = encapsulate ntt;

interface "eth0" {
  send dhcp-client-identifier = hardware;
  request subnet-mask, routers, ip-sip-servers, rfc3442-classless-static-routes, vivso;
  send vendor-class.ntt = concat(06, suffix(hardware, 6));
}
